# Generated by Django 5.2.1 on 2025-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(max_length=5800)),
            ],
            options={
                'verbose_name': 'News German',
            },
        ),
        migrations.CreateModel(
            name='AktuelleArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(max_length=5800)),
            ],
            options={
                'verbose_name': 'News Arabic',
            },
        ),
        migrations.CreateModel(
            name='AktuelleEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(max_length=5800)),
            ],
            options={
                'verbose_name': 'News English',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=4800)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(default='Untitled Program', max_length=80)),
                ('when_starts', models.CharField(blank=True, max_length=80)),
                ('when_at', models.CharField(default='time_zone', max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'Program German',
            },
        ),
        migrations.CreateModel(
            name='ProgramArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(default='Untitled Program', max_length=80)),
                ('when_starts', models.CharField(blank=True, max_length=80)),
                ('when_at', models.CharField(default='time_zone', max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'Program Arabic',
            },
        ),
        migrations.CreateModel(
            name='ProgramEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(default='Untitled Program', max_length=80)),
                ('when_starts', models.CharField(blank=True, max_length=80)),
                ('when_at', models.CharField(default='time_zone', max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'Program English',
            },
        ),
    ]
