# Generated by Django 5.2.1 on 2025-06-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programarabic',
            name='button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programenglish',
            name='button',
            field=models.BooleanField(default=False),
        ),
    ]
