# Generated by Django 5.2.1 on 2025-06-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_program_button_programarabic_button_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.TextField(max_length=15)),
                ('kids', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
