# Generated by Django 4.2.16 on 2025-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_program_img_program_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='img_path',
        ),
        migrations.AddField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='..static/assets'),
        ),
    ]
