# Generated by Django 5.2.1 on 2025-06-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='register',
            name='kids',
            field=models.IntegerField(max_length=1),
        ),
    ]
