# Generated by Django 5.2.1 on 2025-05-27 15:28

import django_dropbox_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_program_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='photos'),
        ),
    ]
