# Generated by Django 5.2.1 on 2025-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_register_age_alter_register_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.TextField(max_length=1),
        ),
        migrations.AlterField(
            model_name='register',
            name='kids',
            field=models.TextField(max_length=1),
        ),
    ]
