# Generated by Django 4.2.16 on 2025-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_program_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktuelleArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(max_length=5800)),
            ],
        ),
        migrations.CreateModel(
            name='AktuelleEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(max_length=5800)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramArabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('title', models.CharField(default='Untitled Program', max_length=80)),
                ('when_starts', models.CharField(blank=True, max_length=80)),
                ('when_at', models.CharField(default='time_zone', max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('title', models.CharField(default='Untitled Program', max_length=80)),
                ('when_starts', models.CharField(blank=True, max_length=80)),
                ('when_at', models.CharField(default='time_zone', max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
