# Generated by Django 4.2.16 on 2025-04-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aktuellearabic_aktuelleenglish_programarabic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktuelle',
            options={'verbose_name': 'News German'},
        ),
        migrations.AlterModelOptions(
            name='aktuelleenglish',
            options={'verbose_name': 'News English'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Programs German'},
        ),
    ]
