# Generated by Django 4.2.16 on 2025-04-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_aktuelle_options_alter_aktuelleenglish_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktuellearabic',
            options={'verbose_name': 'News Arabic'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program German'},
        ),
        migrations.AlterModelOptions(
            name='programarabic',
            options={'verbose_name': 'Program Arabic'},
        ),
        migrations.AlterModelOptions(
            name='programenglish',
            options={'verbose_name': 'Program English'},
        ),
    ]
