# Generated by Django 5.1.7 on 2025-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_aktuellearabic_options_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuelle',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='aktuelles/'),
        ),
        migrations.AddField(
            model_name='aktuellearabic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='aktuelles/'),
        ),
        migrations.AddField(
            model_name='aktuelleenglish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='aktuelles/'),
        ),
    ]
