# Generated by Django 5.2.1 on 2025-05-25 14:26

import storages.backends.dropbox
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_aktuelle_img_aktuellearabic_img_aktuelleenglish_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktuelle',
            name='img',
        ),
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.dropbox.DropboxStorage(), upload_to='programs/'),
        ),
    ]
