# Generated by Django 5.2.1 on 2025-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_aktuelle_img_alter_program_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
