# Generated by Django 5.2.1 on 2025-05-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_program_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktuellearabic',
            name='img',
        ),
        migrations.RemoveField(
            model_name='aktuelleenglish',
            name='img',
        ),
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='https://www.dropbox.com/scl/fo/c1lkv6n40pl0iriwa5d7w/AIs5frr-fLrtS0r6cJKRuMk?rlkey=rn1m67qckojht4symdsx3cbs0&st=evjx2y4t&dl=0'),
        ),
        migrations.AlterField(
            model_name='programarabic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='https://www.dropbox.com/scl/fo/c1lkv6n40pl0iriwa5d7w/AIs5frr-fLrtS0r6cJKRuMk?rlkey=rn1m67qckojht4symdsx3cbs0&st=evjx2y4t&dl=0'),
        ),
        migrations.AlterField(
            model_name='programenglish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='https://www.dropbox.com/scl/fo/c1lkv6n40pl0iriwa5d7w/AIs5frr-fLrtS0r6cJKRuMk?rlkey=rn1m67qckojht4symdsx3cbs0&st=evjx2y4t&dl=0'),
        ),
    ]
