# Generated by Django 5.2.1 on 2025-05-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_aktuellearabic_img_remove_aktuelleenglish_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='programarabic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='programenglish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
