# Generated by Django 5.2.1 on 2025-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_program_img_alter_programarabic_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='programarabic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='programenglish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
