# Generated by Django 5.1.7 on 2025-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Untitled Program", max_length=80)),
                ("when_starts", models.CharField(blank=True, max_length=80)),
                ("when_at", models.CharField(default="time_zone", max_length=80)),
                ("description", models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
